# Generated by Django 3.2.8 on 2021-10-28 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chef', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Data Modificação')),
                ('name', models.CharField(max_length=50, verbose_name='Dome do grupo')),
                ('details', models.TextField(verbose_name='Detalhes do grupo de receitas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Data Modificação')),
                ('name', models.CharField(max_length=50, verbose_name='Receita')),
                ('details', models.TextField(verbose_name='Detalhes da Receita')),
                ('ingredients', models.TextField(verbose_name='Ingredientes')),
                ('method_of_preparation', models.TextField(default='', verbose_name='Modo de Preparo')),
                ('time', models.IntegerField(verbose_name='Preparo (em minutos)')),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chef.chef', verbose_name='Chefe da receita')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipe.grouprecipe', verbose_name='Grupo de receitas')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
            },
        ),
    ]
